### PR TITLE
Kind="Blah" wasn't working

### PR DESCRIPTION
**Pull request by vikasprogrammer**
Moved this.dataStringChanged() outside.

### CODE REVIEW

**Comment by ebidel** [comment]
Before this PR can be merged, please sign the CLA. See the [CONTRIBUTING](http://polymer.github.io/CONTRIBUTORS.txt) guide.

**Comment by ebidel** [comment]
Thanks for signing the CLA!

**Comment by vikasprogrammer** [comment]
My pleasure. Do I need to add myself in that list? 

PS: I have one more PR to submit for `core-submenu`.

**Comment by ebidel** [comment]
Sure. The repo is https://github.com/Polymer/polymer.github.io

**Comment by vikasprogrammer** [comment]
Done.

Regards,
Vikas

**Comment by addyosmani** [comment]
Changes LGTM. Thanks for signing the CLA!

**Pull request merged**
